kind: Service
apiVersion: v1
metadata:
  name: infinispan-site2
  labels:
    clusterName: infinispan
    infinispan_cr: infinispan
spec:
  ports:
    - name: jgroups
      protocol: TCP
      port: 7900
      targetPort: 7900
  selector:
    app: infinispan-pod
    clusterName: infinispan
    infinispan_cr: infinispan
  type: ClusterIP
